<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Lambda : le handler d'une application ASP.NET Core hébergée est le nom de l'assembly. -->
    <AssemblyName>CarteDeVoeuxDebiles.Api</AssemblyName>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarteDeVoeuxDebiles.Core\CarteDeVoeuxDebiles.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="2.2.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.104" />
  </ItemGroup>

</Project>
